development:
  adapter: postgresql
  database: pet_store_dev
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  host: localhost
  username: root
  password: root

test:
  adapter: postgresql
  database: pet_store_dev
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  host: localhost
  username: root
  password: root

production:
  adapter: postgresql
  database: pet_store_dev
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  host: localhost
  username: root
  password: root